version: "3.7"
services:
  playground:
    build:
      context: ./
      dockerfile: dockerfile   # image: toby-playground:v1
    container_name: toby-cp
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "3022:22"
    volumes:
      - /home/toby/docker_share:/workspace/docker_share
    networks:
      - toby-net

  toby-rabbit:
    image: rabbitmq:3.9.5-management
    container_name: toby-rabbit
    volumes:
      - ./packages/begin:/workspace/begin
    networks:
      - toby-net
    

#  toby-redis:
#    image: redis
#    container_name: toby-redis
#    networks:
#      - toby-net


networks:
  toby-net:
    external:
      name: toby-network
