version: "3"
services:
  playground:
    image: toby-playground:v1
    container_name: toby-cp
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "3022:22"
      - "5432:5000"
    volumes:
      - ./document:/home/toby/document
      - /home/toby/docker_share:/workspace/docker_share
