version: "3"
services:
  playground:
    image: toby-playground:v1
    container_name: toby-cp
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
       - "3022:22"
       - "5430:80"
       - "5431:3000"
       - "5432:5000"
       - "8088:8888"
    volumes:
      - ./document:/home/toby/document
      - /home/toby/docker_share:/workspace/docker_share
