FROM ubuntu:20.04
MAINTAINER toby

RUN apt-get update \
    &&  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

RUN TZ=Asia/Taipei \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && apt-get -y install sudo vim \
    curl wget zip unzip tmux git \
    ssh openssh-server

RUN service ssh start
RUN useradd -ms /bin/bash toby && \
    echo 'toby:toby' | chpasswd && \
    usermod -aG sudo toby

USER toby
WORKDIR /home/toby

RUN echo toby | sudo -S apt-get -y install software-properties-common
RUN echo toby | sudo -S add-apt-repository ppa:deadsnakes/ppa
RUN echo toby | sudo -S apt-get -y install python3.8 \
    python3-pip \
    nodejs npm \
    openjdk-8-jre-headless

RUN pip3 install jupyterlab

COPY ./packages/ ./packages/
RUN echo toby | sudo -S chown toby:toby ./packages/kotlin.sh && chmod a+x ./packages/kotlin.sh
RUN ./packages/kotlin.sh


ENTRYPOINT echo toby | sudo -S service ssh restart && /bin/bash
