FROM ubuntu:20.04
MAINTAINER toby
ENV USER_NAME toby

RUN apt-get update \
    &&  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

RUN TZ=Asia/Taipei \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && apt-get -y install sudo vim \
    curl wget zip unzip tmux git nginx \
    ssh openssh-server

RUN useradd -ms /bin/bash $USER_NAME && \
    echo "$USER_NAME:$USER_NAME" | chpasswd && \
    usermod -aG sudo $USER_NAME

USER $USER_NAME
WORKDIR /home/$USER_NAME

RUN echo $USER_NAME | sudo -S apt-get -y install software-properties-common
RUN echo $USER_NAME | sudo -S add-apt-repository ppa:deadsnakes/ppa
RUN echo $USER_NAME | sudo -S apt-get -y install python3.8 \
    python3-pip \
    openjdk-8-jre-headless

RUN pip3 install jupyterlab \
    kotlin-jupyter-kernel \
    opencv-python

COPY ./packages/ ./packages/
COPY ./document/ ./document/
RUN echo $USER_NAME | sudo -S chown -R $USER_NAME:$USER_NAME ./packages && \
    echo $USER_NAME | sudo -S chmod a+x ./packages/language.sh && \
    echo $USER_NAME | sudo -S chown -R $USER_NAME:$USER_NAME /var/www/html

RUN ./packages/language.sh
RUN bash ./packages/init.sh

ENTRYPOINT echo toby | sudo -S service ssh restart && \
           echo toby | sudo -S service nginx restart && \
           /bin/bash
