version: "3.7"
services:
  playground:
    build:
      context: ./
      dockerfile: dockerfile-cp   # image: toby-playground:v1
    container_name: toby-cp
    restart: always
    command: /bin/bash
    stdin_open: true
    tty: true
    ports:
      - "3022:22"
    volumes:
      - /home/toby/docker_share:/workspace/docker_share
    networks:
      - toby-net

  toby-rabbit:
    image: rabbitmq:3.9.5-management
    container_name: toby-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: toby
      RABBITMQ_DEFAULT_PASS: toby
    volumes:
      - ./packages/begin:/workspace/begin
    networks:
      - toby-net

  toby-mongo:
    image: mongo:latest
    container_name: toby-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: toby
      MONGO_INITDB_ROOT_PASSWORD: toby
    volumes:
      - ./packages/begin:/workspace/begin
    networks:
      - toby-net

  toby-mongo-express:
    image: mongo-express:latest
    container_name: toby-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: toby
      ME_CONFIG_MONGODB_ADMINPASSWORD: toby
      ME_CONFIG_MONGODB_URL: mongodb://toby:toby@proj-mongo:27017/
    volumes:
      - ./packages/begin:/workspace/begin
    networks:
      - toby-net


  # toby-interface:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile-flask-restful
  #   container_name: toby-interface
  #   command: /bin/bash
  #   ports:
  #     - "3322:5000"
  #   networks:
  #     - toby-net

#  toby-redis:
#    image: redis
#    container_name: toby-redis
#    networks:
#      - toby-net

networks:
  toby-net:
    external:
      name: toby-network
